DELETE  http://localhost:4001/events/12
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1QHRlc3QuY29tIiwiZXhwIjoxNzMyODMyNjc1LCJ1c2VySWQiOjd9.Fd3JRJde_6cv-tBMYIobYagLbU8q2U4Soe4ACqlzGYM
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QHRlc3QuY29tIiwiZXhwIjoxNzMyODM3Nzg3LCJ1c2VySWQiOjh9.AxIENC95bzHH0TQ48DwvBKN-74FHl93haIyGFarFeL0 
